### ISSUE TITLE
Inform connected peers of name changes

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#502] opened 2024-02-25 20:15 UTC
## Description

@ErikSin brought this up when reviewing the front-end implementation of invites.

Currently when two devices connect over the local network, they share their "device name" as it is defined at the moment that they connect. The device name can be changed after the devices connect, and the connected device should be informed of this change. This is particularly relevant because of the order of operations in a real-life app:

1. User opens Mapeo for the first time
2. Device starts connecting to other Mapeo devices on the local network
3. Device connects and doesn't share a name because it's not defined
4. User enters device name in intro screen
5. Connected devices do not see the device as named until they disconnect and reconnect

## Tasks

- [ ] Send device name to connected peers when it changes
- [x] Emit a new `peers` event when a device receives a new name for a device.

**Comment by EvanHahn** [comment] 2024-03-06 02:08
This looks like a duplicate of #497.

I _think_ this is already done anyway (see [this comment](https://github.com/digidem/mapeo-core-next/issues/497#issuecomment-1961437092)) but I'm going to close in favor of that issue.

**Comment by EvanHahn** [comment] 2024-03-06 15:54
Ah, I was wrong about this. Closed #497 and reopened this.

**Closed** 2024-03-06 20:14 UTC
Labels: mvp
